### ISSUE TITLE
[WIP] Uniform way for working with resolver results

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#102]
In one of [my blog posts](http://bartoszsypytkowski.com/c-a-different-look-at-service-design/) I've shown a way - inspired by Twitter's Finagle - of applying additional logic to service calls. I think we could apply something similar here. It's a proposal and needs some more polishing. 

Given a resolver function like:

```fsharp
type Resolve<'In, 'Out> = ResolveFieldContext -> 'In -> AsyncVal<'Out>
```
we could define a filter for it:

```fsharp
type Filter<'In1, 'In2, 'Out2, 'Out1> = 
    Emitter<'Out1> -> Resolve<'In1, 'Out2> -> ResolveFieldContext -> 'In1 -> AsyncVal<unit>
type Emitter<'Out> = 'Out -> unit
```

What is a filter? It's a wrapper around a resolver, that may apply some additional logic to it. It may (or may not) use emitter to nest value returned from resolver into result set set to user. What we could do with that?:

- It may be used as a general-purpose mechanism to implement directives. Currently we support only two of them (`@skip` and `@include`) and they are handled as special conditions. With filters we could implement directive logic as a filter that will be conditionally compiled into resolution pipeline.
- With emitters we could implement sequential results i.e. [@defer](https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07#8188) directive.

Some example to visualize:

```fsharp
// filter that could be used for @skip directive
let skipDirective emit resolve ctx input = asyncVal {
    let cond = ctx.Arg "if" 
    if not cond 
    then 
        // resolve a value if @skip(if: true)
        let! output = resolve ctx input
        emit output  // emit output to corresponding key-value result set
}
```

**Comment by Horusiath** [comment]
## Emitters

Another idea regarding emitters. Right now we produce result by creating an object graph and serializing it into response stream. What if we provide some abstraction in form of an API (emitter), that will allow us to push data directly into response stream (ignoring object graph construction)? 

How this could work (it's not complete interface): 

```fsharp
type Emitter =
    interface 
        // basic value emitters
        abstract member Emit: bool -> unit
        abstract member Emit: int -> unit
        abstract member Emit: double -> unit
        abstract member Emit: string -> unit
        abstract member EmitNull: unit -> unit
        // list delimeters
        abstract member BeginList: unit -> unit
        abstract member EndList: unit -> unit
        // object delimeters
        abstract member BeginObject: unit -> unit
        abstract member EndObject: unit -> unit
    end
```

When executing a GraphQL statement (query or mutation), we could provide a concrete emitter implementation i.e. for tests we could use emitter that will construct F# objects (as we do now), but for the actual implementation, we could skip this and use emitter which sends data directly to response stream.

With this approach using `@skip` or `@include` directives mentioned above would result in conditional emitting or ignoring emitter for particular fields. 

*Since we're now thinking with streams, we could potentially use emitter, that won't produce a single response (for purposes of HTTP req/response cycle), but possibly produce a continuous stream of responses (for purposes of **GraphQL subscriptions** over i.e. websockets API).*

Things like object/list delimeters would require a hooks into specific level of nesting i.e. before/after we execute all resolvers for some specific object. While this is more work, it could be reused for applying directive filters and to include things like batching logic that needs to be applied to all fields of particular object.

Downside is that usually emitting in stream fashion is a single-pass (although we could hide this as implementation detail). This means that even if we could execute some async requests in parallel, we still need to emit responses in order, but IMO this is pretty edge case.

**Comment by xperiandri** [comment]
If I understand your idea correctly it is already implemented using middlewares. See Middlewares project.
Reopen I it is not what you thought about
