### ISSUE TITLE
Discussion about subscriptions API

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#111]
I'll write here my proposal on the possible subscriptions API. Ok, so what are the most essential operations to make pub/sub pattern working:

- Subscribe
- Unsubscribe
- Publish

### How to represent a stream of events

Now, how do we want to expose a continuous stream of events for a given subscription? Currently `AsyncExecute` returns only a map of result fields and values, parsable directly to output JSON. However in case of subscriptions I can think of at least 3 different cases, i.e.:

```fsharp
type Output = IDictionary<string, obj>
type GQLResponse =
    | Direct of data:Output * errors:string list
    | Stream of events:IObservable<Output>
    | Deferred of data:Output * errors:string list * defer:IObservable<Output>

member x.AsyncExecute(queryOrString): Async<GQLResponse> = ...
````

There are other ways to describe that, but essentially:

- Direct is equivalent of good old request-response mechanism
- Stream is equivalent of subscription only query
- Deferred was initially a case for `@defer` directive, but in this context can be used for any combination of 2 points above.

### How to manage subscriptions

What I think we might want to achieve here is to keep the whole thing agnostic from any specific pub/sub framework or library. What I initially thought of is to extend `SchemaConfig` with pair of two extra callbacks: subscribe and unsubscribe. Those would have been used an extensibility points for users who want to integrate their own subscription mechanisms. 

But when those would be called? As I've show above, a potential output of `AsyncExecute` is `IObservable<>` (FSharp.Control namespace) , therefore:

- **subscribe** would be called when an `AsyncExecute` is called with subscription and `IObservable` response is created.
- **unsubscribe** can be called upon `IObservable<>.Dispose` method (it inherits `IDisposable` interface).
- **publish** - we don't even care about that, as this is something that lies in the hands of user

This is so far what I have for now. It's still rough on the edges, I need to think about it a little more.

**Comment by johnberzy-bazinga** [comment]
Hi @Horusiath 

For the `Stream` case are you referring to the `@stream` directive? If so can't it also be used in conjunction with `@defer` and normal synchronous queries?

**Comment by johnberzy-bazinga** [comment]
I suppose if you use `@defer` and `@stream` together they can use the same observable, but can stream be mixed with a normal response? If the answer is yes, It might be easier to just consolidate the two cases.

**Comment by Horusiath** [comment]
@johnberzy-bazinga no, I'm not touching `@stream` directive here, only `@defer`. When I'm talking about streams I mean subscriptions, as IMHO they are negating the most of the `@stream` directive use cases.

**Comment by johnberzy-bazinga** [comment]
See #110
