### ISSUE TITLE
Upload latest version to Nuget

### ISSUE THREAD

**Issue by imetallica** [fsprojects/FSharp.Data.GraphQL#118]
Hi! I'm trying to use it with a new project that targets NetCore1.1, can you push the `0.0.3-beta` version to nuget?

Thanks in advance,
I.

**Comment by wklm** [comment]
btw is there any nuget package available?

**Comment by Horusiath** [comment]
@wklm you need to enable `-pre` flag on your NuGet (or `prerelease` for Paket). See http://fsprojects.github.io/FSharp.Data.GraphQL/ for details.

**Comment by xavierzwirtz** [comment]
Bumping this again. Looks like the version on nuget is quite old.

**Comment by arthurrump** [comment]
Another bump. The latest NuGet download is almost 1.5 years old now, and it seems quite some changes have been made since then.

**Comment by johnberzy-bazinga** [comment]
@arthurrump @imetallica @xavierzwirtz The latest version 0.0.3 beta is up on nuget with netstandard support. 

[0.0.3-beta](https://www.nuget.org/packages/FSharp.Data.GraphQL.Server/0.0.3-beta
)

Thanks,
John
