### ISSUE TITLE
quick start help VS2017: Server and Shared Projects will not load in newest VS2017-15.2

### ISSUE THREAD

**Issue by hubert-associates** [fsprojects/FSharp.Data.GraphQL#123]
### Description

Getting this error on up-to-date VS2017.
https://developercommunity.visualstudio.com/content/problem/25053/cannot-load-net-core-fsproj-f-in-vs2017.html

F# projects load in general.

### Repro steps

Try to load in VS2017. What tools do you use?

1. Step A

2. Step B

### Expected behavior

Project loads and tests run.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

Windows 10, up-to-date as is the dev env.

Thanks for tips!

**Comment by Horusiath** [comment]
Tbh. I have the same issue after latest merge. /cc @TOTBWF

**Comment by TOTBWF** [comment]
Seems to be caused by Microsoft/visualfsharp#2316.
Their suggested fix is to:

- Download VS 2017 Update 3 Preview 3 (or a further preview if it's released and you're reading this)

- Download the latest CLI/SDK from here: https://github.com/dotnet/cli/tree/release/2.0.0#installers-and-binaries

**Comment by Horusiath** [comment]
Why do we need both VS 2017 15.3 and .net core 2.0 in preview versions? They are highly unstable.

**Comment by TOTBWF** [comment]
We don't need .netcore 2.0, that is just what the people at MS suggested (Not quite sure why). As for solutions, I'm not sure what the best path forward here is, as I was unaware that vs2017 didn't support newer MsBuild features.

**Comment by hubert-associates** [comment]
I'd expect to continue using VStudio for F# as it is our central tool next to vscode, or what do you all use?

**Comment by johnberzy-bazinga** [comment]
We're pretty much all on code, but we should make it work with VS. Are you wanting to work with the source, or are you just needing us to publish a nuget package with latest updates?

**Comment by hubert-associates** [comment]
F# experience lacks to really contribute yet but debugging with the sources is often a big help.  What we (and others) certainly need to get started is a working example -- with packages is fine -- to build upon. Thanks for a great initiative for F#...

**Comment by johnberzy-bazinga** [comment]
This is an old issue and seems to be working with VS now.
