### ISSUE TITLE
Connection definitions should be optional by default

### ISSUE THREAD

**Issue by lxwbr** [fsprojects/FSharp.Data.GraphQL#124]
@TOTBWF as a reminder.

Right now defining a connection produces something like this:

`communities(first: Int, after: String): CommunityConnection!`

but it supposed to be like this according to Relay (if you run Relay's compiler and execute pagination you would run into problems overwise):

`communities(first: Int, after: String): CommunityConnection`

Edit the creation of a connection definition accordingly. (change in the function `connectionOf` or something like this if I remember correctly)

**Comment by Horusiath** [comment]
@zunder in this F# implementation nullability works in reverse - so everything is **non-nullable** by default, as nullability is well expressed via F# `Option` type, while contrary would be almost impossible using F# primitives. 

If you need nullable connections you may mark them with `Nullable(ConnectionOf Type)`.

**Comment by njlr** [comment]
@xperiandri I think we can we close this one?

**Comment by xperiandri** [comment]
@njlr thanks
