### ISSUE TITLE
Type provider error

### ISSUE THREAD

**Issue by baio** [fsprojects/FSharp.Data.GraphQL#126]
### Description

Type provider error

The type provider 'FSharp.Data.GraphQL.Client.GraphQlProvider' reported an error: The server committed a protocol violation. Section=ResponseStatusLine

### Repro steps

1. install FSharp.Data.GraphQL with paket 

2. code

```
#reference "packages/FSharp.Data.GraphQL.Client/lib/net45/FSharp.Data.GraphQL.Client.dll"
open FSharp.Data.GraphQL
type GraphQlClient = GraphQLProvider<"http://api.github.com/graphql">
```

3. Get error on line 3

### Expected behavior

Typeprovider is working

### Actual behavior

Error

```
The type provider 'FSharp.Data.GraphQL.Client.GraphQlProvider' reported an error: The server committed a protocol violation. Section=ResponseStatusLine
```

### Related information 

* Window 10 creator update
* "FSharp.Data.GraphQL.Client": "0.0.2-beta"
* .net46
* Visual Studio Code
* F# interactive

**Comment by Horusiath** [comment]
@baio this may be a bug, but the error message sounds like problem is related to a schema send from the server. Could you provide the schema you're using for this case?

**Comment by baio** [comment]
Hi, I'm not sure about schema what is it? Also I've checked on another gql provider, graph.cool enpoint
```
#reference "packages/FSharp.Data.GraphQL.Client/lib/net45/FSharp.Data.GraphQL.Client.dll"
open FSharp.Data.GraphQL
type GraphQlClient = GraphQLProvider<"https://api.graph.cool/simple/v1/cj4rkf6ui83xx0185n08zulbf">
```
Have following error
```
The type provider 'FSharp.Data.GraphQL.Client.GraphQlProvider' reported an error: The remote server returned an error: (503) Server Unavailable.
```

This provider 100% works if I send there crude graphcool requests  with curl.

**Comment by Horusiath** [comment]
@baio What GraphQL provider essentially does at the start is trying to retrieve a GraphQL schema from the server by sending [this introspection query](https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/src/FSharp.Data.GraphQL.Shared/Introspection.fs#L16) within a `query` query string parameter to provided endpoint. What it expects in response is a GraphQL-compatible JSON for that query, which describes a structure of a server-side schema.

From what I've seen the response from you endpoint is not a valid GraphQL JSON response.

**Comment by johnberzy-bazinga** [comment]
@baio We've completely redesigned the client provider, so I'm closing this as it's out-of-date.
