### ISSUE TITLE
Fragments shallowly merging causes dropped fields

### ISSUE THREAD

**Issue by TOTBWF** [fsprojects/FSharp.Data.GraphQL#129]
### Description

When two parallel fragments are merged, it can cause fields to be dropped. For example:
```
{
  hero(id: "1000") {
    ... T1
    ... T2
  }
}

fragment T1 on Human {
  name
  friends {
    ... on Human {
      name
    }
    ... on Droid {
      name
    }
  }
}

fragment T2 on Human {
  name
  friends {
    ... on Human {
      id
    }
    ... on Droid {
      id
    }
  }
}
```

will only return the `id` field for friends.

The issue is in the planning stage, we merge fragment spreads by their top level fields, and ignore any differences lower down in the tree.

**Comment by johnberzy-bazinga** [comment]
fixed by #133
