### ISSUE TITLE
Allow a json file to be passed into the client type provider

### ISSUE THREAD

**Issue by Kurren123** [fsprojects/FSharp.Data.GraphQL#132]
This will allow us to work offline. The Json file can contain the result of downloading the introspection query that the type provider executes when you pass in a URL. I am willing to submit a PR if I can just manage to open/build this project in Visual Studio/VS Code :) .

**Comment by ivelten** [comment]
I just made a pull request [here](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/149) for that. If you are interested on reviewing it, please do it.

**Comment by ivelten** [comment]
The changes that you asked are being delayed, as there are incoming changes to the type provider system itself.

**Comment by Kurren123** [comment]
Out of curiosity do you have any info about the incoming changes?

**Comment by ivelten** [comment]
We did not continue the changes yet. I had a pull request done for that as I told before, but we decided to wait for the incoming changes on the type provider system. I will take a look on this and see what we can do.

**Comment by ivelten** [comment]
I'll bring back the pull request ASAP. Will notify here when done.

**Comment by ivelten** [comment]
I reopened the Pull Request [here](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/156). Please give your thoughts about it.

**Comment by johnberzy-bazinga** [comment]
@Kurren123 This is complete now in the latest provider. 

You can specify the schema with a file, eg.:
```
type Provider = GraphQLProvider<"schema.json">
```
