### ISSUE TITLE
Support persistgraphql ？

### ISSUE THREAD

**Issue by zaaack** [fsprojects/FSharp.Data.GraphQL#135]
https://github.com/apollographql/persistgraphql

Persistgraphql can reduce request size,  make server safer, and would this be hard to implement?

**Comment by TOTBWF** [comment]
This is actually possible now, and requires no changes to the core library. There are functions in `Executor.fs` that support passing in pre-compiled queries in the form of `ExecutionPlans`. Implementing this specific approach would be as simple as placing some middleware in-between the route that accepts queries and the call to `executor.AsyncExecute`.

**Comment by zaaack** [comment]
I'm not sure I get what you mean, what the persistgraphql do are extracting graphql strings in front end code (statically) and generating a json map with graphql strings and hash ids, the server side can only accept hash ids in the json map file, and get the real query from it.  But you inspired me that we can simply by using buidQuery method to generate the query, we can extract this in runtime like include a module with compile macro,  but still not sure how this can be done with the type provider for now.

**Comment by TOTBWF** [comment]
I'm not very familiar with the inner workings of the client library, but it seems like this is best suited as an extension, and not a core part of the library. If you feel like there are hooks missing, we would be more than happy to see what would need to be done 🙂

**Comment by zaaack** [comment]
@TOTBWF Totally agree. I'll look into further to see what's the best way to implement this.

**Comment by johnberzy-bazinga** [comment]
Closing as this is out-of-scope as an internal feature. From my understanding, this can be introduced outside the library by using a hash of the query as a key.
