### ISSUE TITLE
Implement .Net Standard 2.0?

### ISSUE THREAD

**Issue by randy-r** [fsprojects/FSharp.Data.GraphQL#138]
Will there be support for `.net standard 2.0` any time soon?

**Comment by johnberzy-bazinga** [comment]
We currently support `net standard 1.6` on the server which is compatible with `netcoreapp 2.0`. Also, we just added support for `net standard 2.0` and the new TP Authoring SDK for the client library. We can add  `net standard 2.0` support to the server library fairly easily, but I'm not sure if there is any particular advantage to adding that. Please let me know if that addresses your question.

Thanks

**Comment by johnberzy-bazinga** [comment]
@randy-r Closing as this is complete in #145
