### ISSUE TITLE
Subscriptions and websockets (QUESTION)

### ISSUE THREAD

**Issue by easysoft2k15** [fsprojects/FSharp.Data.GraphQL#139]
Hi,
seems like Subscriptions are used in the following example:
https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/samples/graphiql-client/server.fs
I'd expect Subscriptions data being returned on a web socket but in the example I see that Suave server respond only when polled.
My expectation with subscription would be to:
1. subscribe to wanted data on client side
2. receive data asynchronously from server whenever new data are available (presumably over a websocket).

Is something missed from the example?
I would expect something like this (Pseudocode):
```
let ws (webSocket : WebSocket) (context: HttpContext) =
  socket {
    let mutable loop = true
    while loop do
        //Get Subscription data change event here somehow......
        .....
       
        //GraphQL Process data....
        let! result = Executor(schema).AsyncExecute(...)
       
        // the response needs to be converted to a ByteSegment
        let byteResponse =
          result
          |> System.Text.Encoding.ASCII.GetBytes
          |> ByteSegment

        do! webSocket.send Text byteResponse true
        ......
```

 Could You please give some hint or point me to a resource showing how to accomplish a similar task?
Thank You

**Comment by TOTBWF** [comment]
The basic structure would be as follows:

1. Define a `SubscriptionField` for your subscription.
2. `AsyncExecute` will return a `GQLResponse`, which is a DU with 3 cases: `Direct` for a normal response, `Deferred` for queries with the `@defer` directive, and `Stream` which is used for subscriptions
3. The `Stream` case contains an `IObservable`, which will publish whenever the subscription is fired via invoking `schemaConfig.SubscriptionProvider.Publish<T> "nameOfTheSubscriptionField" valueToPublish`.
4. In the `Observable.subscribe` call, send the data down the websocket connection

Hope that helps!

**Comment by easysoft2k15** [comment]
That's exactly what I was looking for!
Thank You
