### ISSUE TITLE
Visual Studio 2017 Fails to Load .Server and .Shared

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/FSharp.Data.GraphQL#140]
### Description

I branched and clones the project.  When I open it locally, I am getting this error
![image](https://user-images.githubusercontent.com/1394644/35486840-fe41b4ea-0441-11e8-9a47-7ed9cbe344d5.png)

### Repro steps

Please provide the steps required to reproduce the problem

1. Branch

2. Clone

3. Open in VS2017

### Expected behavior

All project load

### Actual behavior

.Server and .Shared fail to load

### Known workarounds

None

### Related information 

* Win 10
* Dev branch
* NA

**Comment by johnberzy-bazinga** [comment]
@jamessdixon Can you try reproducing this off of[ my branch](https://github.com/johnberzy-bazinga/FSharp.Data.GraphQL)? I've started fixing the build and moving to the newer SDK, but I'm working off of OSX and using VS Code, so I'm not sure if it works on Windows with VS.

Thanks

**Comment by jamessdixon** [comment]
Same error
:-(

**Comment by johnberzy-bazinga** [comment]
@jamessdixon Thanks for taking a look. I tested on parallels and was able to successfully load and build the project. You need to run build.cmd first so paket.bootstrapper.exe downloads Packet.Restore.Targets. Also, I believe you need VS 2017 15.5.5 installed.

Thanks,
John

**Comment by johnberzy-bazinga** [comment]
@jamessdixon I have merged the changes from my fork in. Also, I included paket.restore.targets so you no longer need to run anything before opening the sln. Tested on a windows VM with VS 2017 15.5.5. Please let me know if you come across any issues.

Thanks

**Comment by jamessdixon** [comment]
That did it - thanks

**Comment by jamessdixon** [comment]
That did it - thanks
