### ISSUE TITLE
Optional input arguments with defaultValues are not creating a correct schema in server

### ISSUE THREAD

**Issue by Zeroto** [fsprojects/FSharp.Data.GraphQL#167]
### Description

When creating an optional input argument the schema it generates is incorrect.
e.g. when having `Define.Input("test", Boolean, defaultValue = true, description = "test")` the output schema marks the field as non-nullable. But when you make it nullable `Define.Input("test", Nullable Boolean, defaultValue = Some true, description = "test"` then the schema puts `Some(True)` as the default value which is not a valid boolean value.

Preferably the fields should be marked as nullable in the schema when it is given a default value in the definition without requiring it to be made a nullable type. From the view of the resolver the value is always supplied so it does not make a lot of sense of it being an Option which a nullable type enforces.

### Repro steps

2 scenarios:
a) Create a graphql field with a nullable input with a boolean default value.

b) Create a graphql field with an non-nullable input with a boolean default value.

### Expected behavior

a) The schema generated should be valid by having `True` as the default value.

b) The schema should mark the input argument as a nullable argument

### Actual behavior

a) The schema generated is invalid because of `Some(True)` as the default value

b) The schema is valid but the field is marked as non-nullable(and thus required) which doesn't make sense for a field with a default value

### Known workarounds

Don't mark the field as nullable. Most clients don't validate the queries against the schema.

**Comment by ivelten** [comment]
This makes sense to me. I made a pull request for that [here](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/168). @Horusiath, what do you think about it?
