### ISSUE TITLE
Issue with Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by thitemple** [fsprojects/FSharp.Data.GraphQL#170]
### Description

I'm trying to use this library and I'm having the following issue:

> The type provider 'FSharp.Data.GraphQL.Client.GraphQlProvider' reported an error: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

The paket.lock file says I have version `Newtonsoft.Json (11.0.2)` installed. I'm using the latest `Fable.Compiler (1.3.17)` which has a dependency on version 11.0.1 or later of Newtonsoft.

### Repro steps

I added a dependency to this library using Paket in an existing project using the latest version of the Fable.Compiler and tried to open the module:

![2018-07-16 12_21_43-window](https://user-images.githubusercontent.com/368734/42770878-65a6400c-88f3-11e8-8647-51387cb0f2b2.png)

* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: Target is netstandard2.0, I'm running on .net core 2.1

**Comment by Horusiath** [comment]
Tbh. I think, we could drop the json serializers all along. In essence when we construct a GraphQL response, we already produce a full JSON tree representation, that could be encoded as:

```fsharp
type GQLReply = 
    | GQInt     of int
    | GQLFloat  of double
    | GQLString of string
    | GQLBool   of bool
    | GQLNull
    | GQLList   of GQLReply list
    | GQLObj    of struct(string * GQLReply) list
```

You don't need an entire JSON.NET to serialize such structure. A simple function can do that, see: https://github.com/Horusiath/Grafs/blob/8cf29fd50dc11ff21bc72c18d4794c009825745d/src/Grafs/Execution.fs#L33

**Comment by ivelten** [comment]
I agree. We could work at this change ASAP, as this dependency can lead to many issues like that on the provider.

**Comment by thitemple** [comment]
In the meantime do you have an idea of a workaround? Or do you want to point me in the direction on how to fix it? I could submit a PR

**Comment by ivelten** [comment]
I think I need to discuss the changes a bit better. In the meantime, we could perhaps approve this [Pull Request](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/171), which updates Newtonsoft.Json dependencies to their last versions?

**Comment by bbhoss** [comment]
It appears that this has popped back up, maybe a new version has been released and it needs to be bumped again? Any way to get this going right now? I was hoping to demo the GraphQL type provider stuff to friends but I can't get it working on Mac or Windows.

**Comment by ivelten** [comment]
@bbhoss sorry for the delayed response. I'm working on a permanent solution for that [here](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/182).

**Comment by bbhoss** [comment]
No worries. I am happy to try to help but it might take more work to get me up to speed than it's worth. I tried pulling your fork down and couldn't get it to build, fwiw. Thanks :)

**Comment by ivelten** [comment]
@bbhoss I fixed the build script on my last push. Please, see if it works now. I believe that code that I added will solve the problem.

**Comment by bbhoss** [comment]
I finally got it to build on my mac after wiping out an ancient Mono version and removing the net47 targeting. Now I'm hitting #153 :( I will check this later on my Windows machine though. Thanks for the help so far. Any insight into that other issue would be really helpful as well. I'm available via other modes as well; would love to help get this going on .NET Core.

**Comment by bbhoss** [comment]
Just tested on Windows with VS2017 and .NET 4.6. It still complains with this error

**Comment by ivelten** [comment]
OK, thanks for the information so far. I am diagnosing those cases and looking for the solution.

**Comment by ivelten** [comment]
@bbhoss Sorry for the very long delay in this. I found the solution for it, but it required me to restructure many things in the client project. I'm finishing those changes and will be opening a PR for this.

**Comment by ivelten** [comment]
@bbhoss The pull request with your features is [here](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/179). I made the client compatible with .NET 4.7, .NET Core 2.1 and .NET Standard 2.0.

**Comment by albertwoo** [comment]
When can we merge it and release it? Because currently I have a similar issue, when I use the provider, it says cannot load "Newtonsoft.Json, Version 11.0.0.0"

**Comment by johnberzy-bazinga** [comment]
Closing as we no longer use Newtonsoft.Json in the client provider.
