### ISSUE TITLE
Type provider does not map fields with arguments

### ISSUE THREAD

**Issue by ivelten** [fsprojects/FSharp.Data.GraphQL#183]
### Description

Currently, the client type provider is not supporting fields with arguments.

### Repro steps

1. Run the Giraffe web server sample.

2. Create a console application and put this code on `Program.fs` file:

```
open FSharp.Data.GraphQL

let [<Literal>] ExitCode = 0
let [<Literal>] Url = "http://localhost:8084"

type MyClient = GraphQLProvider<Url>

[<EntryPoint>]
let main _ =
    async {
        let! hero = MyClient.Queries.Hero("1000", fun c ->
                    Fields(
                        c.name,
                        Selection(c.friends, fun f -> Fields(f.name)),
                        MyClient.Types.Human.On(fun h -> Fields(h.appearsIn))
                    ))
        match hero with
        | None -> ()
        | Some hero ->
            printfn "My hero is %A" hero.name
            printfn "Appears in %O: %b" MyClient.Types.Episode.Empire
                (hero.appearsIn |> Array.exists ((=) MyClient.Types.Episode.Empire))
            printfn "My hero's friends are:"
            hero.friends
            |> Array.choose (fun x -> x.name)
            |> Array.iter (printfn "- %s")
    }
    |> Async.StartImmediate
    ExitCode
```

### Expected behavior

The `friends` field of the `Human` type is using an argument created from a middleware to filter lists. This field is optional. It would be good if this field could be exposed as a function using the original field arguments as parameters, for example.

### Actual behavior

The `friends` field is not mapped at all (we get a design time error `The field, constructor or member 'friends' is not defined.`)

### Known workarounds

Do not use arguments on fields inside query or mutation objects.

### Related information 

* Microsoft Windows 10 Pro (10.0.17134)
* dev branch
* .NET Core 2.1

**Comment by johnberzy-bazinga** [comment]
Old issue. Closing as the entire TP was redesigned.
