### ISSUE TITLE
Top level field name missing in subscriptions

### ISSUE THREAD

**Issue by Zeroto** [fsprojects/FSharp.Data.GraphQL#193]
### Description

When using subscriptions, the top level field of the subscription is missing in the return data. Apollo expects the field to be present. This also creates problems when having multiple subscriptions in one operation. e.g.
```
subscription s {
  comments(thread: "A") {
    text
  }

  second: comments(thread: "B") {
    text
  }
}
```

### Repro steps

1) Define a schema that accepts the following subscription:
```
subscription s {
  testTime {
    time
  }
}
```

2) Subscribe to this subscription.

### Expected behavior

The data returned in the subscription should have the following format:
```
{
  data: {
    testTime: {
      time: "2018-11-29T14:54:44.5584148+01:00"
    }
  }
}
```

### Actual behavior

The data returned is missing the testTime field and returns the inner object
```
{
  data: {
    time: "2018-11-29T14:54:44.5584148+01:00"
  }
}
```

### Known workarounds

none

### Related information 

Version 0.0.12-beta

**Comment by Zeroto** [comment]
Looking at the spec ([https://facebook.github.io/graphql/June2018/](https://facebook.github.io/graphql/June2018/)) it seems that you can only have 1 root level field in the subscription query. [https://facebook.github.io/graphql/June2018/#sec-Subscription-Operation-Definitions](https://facebook.github.io/graphql/June2018/#sec-Subscription-Operation-Definitions)  
So you can ignore the example I gave in the description. This should probably cause an error though. Atm it is ignored.

The spec also shows that the root level field should be included in the output. [https://facebook.github.io/graphql/June2018/#example-2a5f0](https://facebook.github.io/graphql/June2018/#example-2a5f0)

**Comment by johnberzy-bazinga** [comment]
@Zeroto I've included the fix for the top-level field name in #194 and released an update on Nuget. Thanks for the report!

**Comment by Zeroto** [comment]
@johnberzy-bazinga Thanks! I'm using the new version and it seems to work fine 😃

**Comment by johnberzy-bazinga** [comment]
Great!
