### ISSUE TITLE
DirectiveLocation not up to date

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharp.Data.GraphQL#195]
### Description

I noticed that [the spec](https://facebook.github.io/graphql/June2018/#sec-Introspection) now has more enum values for [DirectiveLocation](https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/src/FSharp.Data.GraphQL.Shared/Introspection.fs#L115).

Would you accept a PR for this? I would like to add them.

My concrete use-case is using the client TypeProvider, and my backend returns newer directive locations when doing introspection so it currently doesn't work.

**Comment by ivelten** [comment]
I think it's fine to subimit a PR for this.
