### ISSUE TITLE
Remove newlines from IntrospectionQuery

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharp.Data.GraphQL#196]
### Description

When trying the client TypeProvider it returns 404 when only passing the url.

### Repro steps

```fsharp
#load ".paket/load/net472/main.group.fsx"

open FSharp.Data.GraphQL
type GraphQLClient = GraphQLProvider<"http://localhost:5000/api/graphql/GetAsync">
```

### Expected behavior

Server returns json and TypeProvider kick in.

### Actual behavior

TypeProvider fails due to 404.

### Known workarounds

When I looked into the code, I saw [requestSchema](https://github.com/fsprojects/FSharp.Data.GraphQL/blob/34a5ea5d325aeb9de161e935d5c8b2315ccd2a0a/src/FSharp.Data.GraphQL.Client/GraphQlProvider.fs#L54). However the query contains newlines that is the problem I believe.

```fsharp
let requestSchema (url: string) =
    async {
        let query =
            FSharp.Data.GraphQL.Introspection.introspectionQuery
                .Replace("\n", String.Empty)
        let requestUrl = Uri(Uri(url), ("?query=" + query))
        printfn "req url %A" requestUrl
        let req = WebRequest.CreateHttp(requestUrl)
        req.Method <- "GET"
        use! resp = req.GetResponseAsync() |> Async.AwaitTask
        use stream = resp.GetResponseStream()
        use reader = new StreamReader(stream)
        let! json = reader.ReadToEndAsync() |> Async.AwaitTask
        return json
    }
```

This pseudo function did work for me, removing the newlines is necessary.
Could be a Windows thing. Would you accept PR?

### Related information 

* Operating system: Windows 10
* Branch: dev
* .NET Runtime, CoreCLR or Mono Version: net472

**Comment by ivelten** [comment]
Are you using our component to build the server? Actually, we are manually removing the line breaks in the server code, not on the client queries. You can see this on our Giraffe Server sample:

```fsharp
let removeSpacesAndNewLines (str : string) = 
    str.Trim().Replace("\r\n", " ")
let readStream (s : Stream) =
    use ms = new MemoryStream(4096)
    s.CopyTo(ms)
    ms.ToArray()
let body = readStream ctx.Request.Body
let query = body |> tryParse "query"
let variables = body |> tryParse "variables" |> mapString
match query, variables  with
| Some query, Some variables ->
    printfn "Received query: %s" query
    printfn "Received variables: %A" variables
    let query = query |> removeSpacesAndNewLines
```

**Comment by nojaf** [comment]
I'm not using this package for my backend. So I guess that  would explain everything.
I'm using [graphql](https://github.com/graphql-dotnet/graphql-dotnet) in C#.

**Comment by johnberzy-bazinga** [comment]
@nojaf Closing as I think it's something specific to the server implementation being too sensitive with whitespace. Also, the TP has been completely redesigned so this might not apply anymore.
