### ISSUE TITLE
Add authentication to TypeProvider.

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharp.Data.GraphQL#197]
### Description

It is currently not possible to add any form of authentication to the client TypeProvider.
At runtime I would need to add some Authentication header.

**Comment by ivelten** [comment]
This could be interesting, unfortunately, we are focusing more on the server at the moment. If you have an idea of implementation, feel free to submit a pull request, we can review and discuss it laters.

**Comment by nojaf** [comment]
Was able to add headers with beta3.
