### ISSUE TITLE
Change url of TypeProvider at runtime

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharp.Data.GraphQL#198]
### Description

Not entirely sure if this is an issue, but I would need to change the url of my backend at runtime to point to a different stage. Is this possible in the TypeProvider.

<sub>PS: Sorry for logging all these issues, got a bit carried away and I just really want to do something with this project.</sub>

**Comment by ivelten** [comment]
AFAIK, this is not possible. It's an interesting feature, but unfortunately we can't work on this at the moment. I worked on a kinda big pull request to update our dependencies and solve some of the type provider problems with dependencies [here](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/179). You are welcome to open a pull request to add this feature if you want to.

**Comment by johnberzy-bazinga** [comment]
@nojaf We're rewriting the provider and this is accounted for in the new version. The Pull request for the work is
https://github.com/fsprojects/FSharp.Data.GraphQL/pull/179

It should be released in the coming days.

**Comment by nojaf** [comment]
Great news! Many thanks for everybody's hard work.

**Comment by nojaf** [comment]
Works with beta3.
