### ISSUE TITLE
What has happened to AsyncVal?

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#214]
The sole purpose of [AsyncVal](https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/src/FSharp.Data.GraphQL.Shared/AsyncVal.fs) was to provide capability of composable low-overhead, high performance continuation with fast track for immediately resolved values (pretty much what `ValueTask<>` is for `Task<>`). It was simple value type with 2 possible states. From what I see, now it's neither value (resulting in extra of allocations), nor it finishes on 2 states.

**Comment by johnberzy-bazinga** [comment]
You're absolutely right. I completely missed this change in one of the PRs and we should turn it back into a struct so it doesn't allocate.

I'll go through the codebase in the next few weeks and try to improve some of the performance bottlenecks and regressions.

**Comment by johnberzy-bazinga** [comment]
Looks like it was introduced in this PR:

https://github.com/fsprojects/FSharp.Data.GraphQL/commit/be8040590d89af7ea323185bbb24658154fcb9e1#diff-6f48d92a67c3f2191a77201751948bef

**Comment by johnberzy-bazinga** [comment]
We've changed it back to a Struct.
