### ISSUE TITLE
Authentication header in `GraphQLProvider`

### ISSUE THREAD

**Issue by lucasteles** [fsprojects/FSharp.Data.GraphQL#215]
### Description

Have we some way to pass an authentication header in `GraphQLProvider` ? 
I'm trying to use the github graphql API, but he needs a bearer token

### Repro steps

```cs
type GraphQlClient = GraphQLProvider<"https://api.github.com/graphql">
```

dont compile,  gives error:

```
FS3033	The type provider 'FSharp.Data.GraphQL.Client.GraphQlProvider' reported an error: The remote server returned an error: (403) Forbidden.
```

**Comment by johnberzy-bazinga** [comment]
@lucasteles We'll look at introducing a static parameter for the Authorization header.

/cc @ivelten

**Comment by johnberzy-bazinga** [comment]
@lucasteles this has been introduced now. Please let us know if you come across any issues.

Thanks

**Comment by pottereric** [comment]
Is there an example of how to use this?

**Comment by pottereric** [comment]
Nevermind, I found the sample code in the repo.
