### ISSUE TITLE
Enums as variables returns an error

### ISSUE THREAD

**Issue by Zeroto** [fsprojects/FSharp.Data.GraphQL#216]
### Description

Enums are currently not supported as a variable type in the server. According to the spec an Enum is a valid input type: https://graphql.github.io/graphql-spec/June2018/#IsInputType()

### Repro steps
1) Define a schema with an enum type.
2) Try to use that type as a variable

e.g.
The type definition
```
let enumTestType = 
  Define.Enum
    ("EnumTestType"
      , [ Define.EnumValue("Foo", EnumTestType.Foo)
          Define.EnumValue("Bar", EnumTestType.Bar)
        ]
      , "Test enum"
    )
```
Trying to use it as a variable
```
query test($data: EnumTestType!) {
  testData(data: $data) {
    test
  }
}
```

### Expected behavior
Enum is parsed properly and can be used in the resolver

### Actual behavior
An error is returned: `FSharp.Data.GraphQL.GraphQLException: Variable '$data': Only Scalars, Nullables, Lists and InputObjects are valid type definitions.`

### Known workarounds
Wrap the enum in an inputObject

**Comment by johnberzy-bazinga** [comment]
Thanks for the report. We'll look at fixing this as part of the next release.

**Comment by johnberzy-bazinga** [comment]
@Zeroto this is fixed in the latest server now.
