### ISSUE TITLE
FSharp.Data.GraphQL.Shared nuget; Release tags

### ISSUE THREAD

**Issue by andymeierdev** [fsprojects/FSharp.Data.GraphQL#222]
### Description

First would like to say awesome project. Thanks for the great work!

Trying out 1.0.0-beta2 I see that `FSharp.Data.GraphQL.Types` has moved to `Shared` project. I don't see a nuget package for this and was wondering what is the correct way to reference?

Also, would it be possible to create a git tag on new releases? It is helpful for me to reference the state of the code at a particular release so I can debug if I am using the library correctly. Happy to create a PR for this.

**Comment by johnberzy-bazinga** [comment]
Hi @ameier38

Thanks!

The Shared project is currently included in the Client/Server nuget packages as an additional assembly. There is an open PR that we haven't merged yet to extract it out into another package. 

As for release tagging, what were you thinking? We currently deploy to Nuget manually, but we would be happy to consider automating the tagging process.

 Thanks,
John

**Comment by andymeierdev** [comment]
Cool thanks. I think you could leverage https://fake.build/apidocs/v5/fake-api-github.html to publish a release. I can put together a PR to add to the build script if that would be helpful.

**Comment by johnberzy-bazinga** [comment]
There was a bug with the packaging where the shared library was not included. Should work with beta9.

Thanks

**Comment by xperiandri** [comment]
@ameier38 both implemented

**Comment by xperiandri** [comment]
Use the latest preview packages from the GitHub feed
