### ISSUE TITLE
Is it possible to pass down functions/variables inside an object resolver ?

### ISSUE THREAD

**Issue by klanthier** [fsprojects/FSharp.Data.GraphQL#232]
### Description

This is not exactly an issue per say, but more a question.

After you have built your schema of object resolvers, you get your query as an input in your server and you process it using the Schema executor to get the reply from whatever your query was.

At the point where you execute the schema 
```
executor.AsyncExecute(
   ast = parse q
) |> Async.RunSynchronously
```

Is it possible somehow here to pass down some top level logging function/variables so that when you are inside your object resolvers, you can have access to them ?

**Comment by johnberzy-bazinga** [comment]
Certainly. AsyncExecute takes a `data` parameter which is accessible via the `ResolveFieldContext` (the first parameter to the resolve function). The root object is not typed when you access it through the context, but you can create an extension member so you don't need to downcast it everywhere.


```
    type Root = { Logger : ILogger } 

    type ResolveFieldContext with
        member this.Root : Root = downcast this.Context.RootValue
```

Your top-level fields i.e. query, subscription, mutation should look something like below:

```
let Query = Define.Object<Root>(
        name = "Query"
...
```

**Comment by klanthier** [comment]
Thanks a bunch !

For those looking at this, that's how I did it :

```
module Api.Types

    type GraphQLExecutionContext = { Logger : (string -> unit) } 
    type FSharp.Data.GraphQL.Types.ResolveFieldContext with
        member this.Root : GraphQLExecutionContext = downcast this.Context.RootValue
```

```
let executionContext: Api.Types.GraphQLExecutionContext = {
    Logger = (fun x -> context.Logger.Log(x))
}
let document = parse q

executor.AsyncExecute(document, executionContext) |> Async.RunSynchronously
```

This way you can pass down arguments or whatever function you might need for your resolvers.

In my case, I needed to pass down the logger since I'm using AWS Lambda and the logger function is only given from the entry point
