### ISSUE TITLE
Apply validation rules

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#24]
Right now query and schema validation is very residual. There are a lot more validation rules specified in [official GraphQL spec](https://facebook.github.io/graphql/), which should be implemented. Additional task for this issue is to specify all necessary rules.

Some of the rules:
- Valid query must result with the tree graph, where every leaf satisfies `LeafDef` (so it's either a scalar or enum) or is list/non-null wrapper of that type.
- It's not allowed to query fields of interfaces, which are not defined in the interface itself, even when implementing object has queries field.
- Interface must define at least one field.
- Interface and object field names must be unique in scope of given interface/object. Duplicates should throw errors.
- If objects satisfy interface, correlated field definitions (having the same name) must share same type.
- It's not allowed to query fields of unions without specifying (using fragments), which of the union's options are we referring to.
- Union type must define at least one option type.
- Input object must define at least one field.
- All of the input object's fields must satisfy `InputDef`.
- NonNull type cannot wrap another NonNull type (however for example: `NonNull (ListOf (NonNull Int))` is allowed.
- All queried fields must be defined in scope of their types. It's not allowed to query field not defined in its type.
- Fields and field aliases must have unique names (they share the same namespace).
- In case of unions of objects sharing field names, returned field type must be the same (it's not allowed to query field X in union of `A|B` given the following definitions `object A { X: Int } object B { X: String}`.
- It's invalid to treat `LeafDef` as `CompositeDef` - it must remain a leaf of the query tree.
- It's not allowed to provide arguments on fields which no arguments were defined.
- It's not allowed to provide arguments of incompatible names or types.
- It's not allowed to query fields without providing all of the necessary argument values (only arguments with default values specified can be omitted).
- Fragment names must be unique in scope of the query.
- It's not allowed to query fragments not defined in schema.
- It's not allowed to query fragments on types not satisfying `CompositeDef`.
- Fragment defined in query must be used by that query at least once.
- Query cannot refer to fragments, it didn't specified.
- Fragments must not form cycles.
- Directives must be in valid locations.
- Variables must be unique in scope of a query.

**Comment by johnberzy-bazinga** [comment]
This has been released now. Available in the 1.0.0 package onwards. It's utilized in both the client and server libraries.
