### ISSUE TITLE
Question: Why overloads instead of optional parameters?

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/FSharp.Data.GraphQL#250]
Edit:

I'm giving the FSharp.Data.GraphQL client provider another try, since it's been a few months.  Looks like I'm not running into the same errors I got last time.

One thing I notice is that when I create an operation using a query like so:

```fsharp
let op = B.Operation<"""            query ($uId:Int, $rId:Int, $sinceTimestamp:String, $first:Int, $offset:Int) {
              answer(id: $rId) {
                agreed_users (sinceTimestamp:$sinceTimestamp, first:$first, offset:$offset) {
                    id
                    is_verified
                    username
                    avatar
                    follows_status(uId: $uId)
                }
              }
            }""">()
```

`op.Run` creates an overload for every permutation of parameters, plus a runtime context.

Is there any reason [optional parameters](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments#optional-parameters) were not used instead?  Seems like it would be much easier to read and use, and probably more performant too.  If there's no particular reason, is that something you would consider?

**Comment by NatElkins** [comment]
Sorry, accidentally hit enter, ignore while I actually type out my question

**Comment by johnberzy-bazinga** [comment]
@NatElkins Originally we did have optional parameters but made [this](https://github.com/fsprojects/FSharp.Data.GraphQL/commit/3253120ef805ec265a56362e0975de7bf9f434fb) change. There was good reason for it, but I can't recall exactly what that was.

**Comment by NatElkins** [comment]
I just ask because I get stuff like this (even though I know this isn't specifically for an `Operation`):

<img width="702" alt="Screen Shot 2019-10-09 at 9 15 30 AM" src="https://user-images.githubusercontent.com/1795462/66485840-76ffe380-ea77-11e9-88c5-e67cbfefae7e.png">

Notice the number of overloads...just absolutely annihilates Intellisense, memory use goes through the roof.  This is for a type that looks like this:

```graphql
input AddUserInput {
  uId: Int!,
  uName: String!
  fName: String
  lName: String
  email: String
  phone: String
  avatar: String
  is_popular: Boolean
  is_verified: Boolean
  is_vip: Boolean
  is_suggested: Boolean
  is_influencer: Boolean
  is_mascot: Boolean
  is_employee: Boolean
  last_app_open: String
  created: String
  updated: String
}
```

If you're able to remember what that reason was, I'd be really curious to know.

**Comment by NatElkins** [comment]
Just thought I'd swing back around to this.  @ivelten Do you remember why the change was made?

**Comment by ivelten** [comment]
@NatElkins as you said, yes, we originally designed type constructors to use optional parameters for their properties. But we faced a problem with the Type Provider SDK itself and nullable/option types.

The SDK does not allow us to use an option or nullable type as an optional argument when declaring a provided constructor - at least not if we don't provide a default value for it. But the design around it does have its own complications. I opened an [issue in the Type Provider SDK repository](https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/312) that explains better this problem.

Basically, if we create an optional argument, we need to provide a default value. And if the optional argument is a value type, it does not have an "empty" definition, so there is no way to know if the user passed or not a value. Even when we get the default value, there is no way to determine if this value came as an omission of the optional parameter by the user, or if this value actually came of the user providing it.

Using a practical example, if the optional argument is an `int` type, and the default value is `0`, when the user does not provide a value, we can't say if `0` was given by the user or is just the default value that came by the omission of a value in the optional parameter. So, in the end, we would not be able to know if the optional property, which is an `int option`, should receive `Some 0` or `None`.

Based on this issue, we decided that overloads would be the best workaround. As optional parameters are treated as overloads in the IL, we thought that in practice, the result of it running would not change. I also did test it with around 10.000 overloads and did not notice an impact at the time.

If this problem turns things unusable, I think we would need to think about the other workaround in the issue. Or discuss any other alternative that we did not think of at the time.

**Comment by NatElkins** [comment]
@ivelten Thanks for the comprehensive writeup.  I'll have a think about it.

**Comment by johnberzy-bazinga** [comment]
@NatElkins one option is to just generate our methods with explicit options rather than creating all the overloads. Maybe even providing both options and parameterize the new behaviour.

```
type MyApi = GraphQLProvider<"schema.graphql", explicitOptionalParameters=true>
let input = MyApi.Types.MyInput(x = "required", y = Some "optional")
```

**Comment by ivelten** [comment]
I like this design. It gives the user the option to adjust it when a lot of overloads mess up the usability because of the way the provider system works.

**Comment by NatElkins** [comment]
Agreed it seems like it would be a big improvement.

**Comment by bddckr** [comment]
Hey everyone! I've run into this issue and have raised a PR as linked above (#312). I'm hoping to get some feedback on the PR page, and ultimately get this merged of course 😄

In my case I've not been able to observe any issue with IDE performance or the likes, however I have some GraphQL types in my schema that force me to call more than 15 different constructor permutations for a single type alone, due to wanting to pass some optional arguments (which are all completely independent).
