### ISSUE TITLE
TypeProvider runs out of control with certain schema/operation

### ISSUE THREAD

**Issue by aggieben** [fsprojects/FSharp.Data.GraphQL#256]
**Describe the bug**

When opening a specific .fsx file that makes use of a type provider, the .NET Core Host used by Ionide loses its mind and hogs all the CPU and memory.  Pretty spectacularly:

![image](https://user-images.githubusercontent.com/1321/67907463-eed89f80-fb45-11e9-9c6f-2155e9ee8937.png)

I did also try this with Visual Studio 2019, and it exhibited similar behavior, although after trying it with VS it seems to be specifically caused by this operation:

```F#
let updateOperation =
  AdminAPI.Operation<
      """
      mutation UpdateProduct($input: ProductInput!) {
          productUpdate(input: $input) {
              product {
                  id
              }
              userErrors {
                  field
                  message
              }
          }
      }
      """
      >()
```

See attached files below for the schema and full script.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the latest FSharp.Data.GraphQL repository
2. In the `samples/client-provider` folder, add the following files: `shopify_tests.fsx`, `shopify.json`
provided here: [client-provider.zip](https://github.com/ionide/ionide-vscode-fsharp/files/3791538/client-provider.zip)
3. Open the root `FSharp.Data.GraphQL` workspace in VSCode 
4. Open `shopify_tests.fsx`
5. Observe the .NET Core Host go bonkers

**Expected behaviour**

I would expect this to not happen :-)

**Screenshots**
See above

**Environment (please complete the following information):**
 - OS:  Windows 10
 - Ionide version: 4.2.0
 - VSCode version: 1.39.2
 - dotnet SDK version: 3.0.100
 - mono / .Net Framework version: 4.8.03752

**Additional context**

**Comment by moinessim** [comment]
Hi @aggieben,
I’m having a similar issue. 
Did you find a workaround?

**Comment by xperiandri** [comment]
Try again with the latest version from the GitHub feed. Feel free to reopen
