### ISSUE TITLE
GraphQL operations with arguments of Custom Scalar Types don't run properly via GraphQLProvider

### ISSUE THREAD

**Issue by ZhenyaP** [fsprojects/FSharp.Data.GraphQL#272]
### Description

I am trying to use Custom Scalar Type in GraphQL Server schema as the type for some input/output fields for queries/mutations.
I am using the latest version (1.0.5) of FSharp.Data.GraphQL.Client and FSharp.Data.GraphQL.Server packages.
On the client, when I am running a query with passing the Query field argument value (that is of this Custom Scalar Type) via GraphQLProvider,
I am getting the following exception:
{"Expected type to have a \"__typename\" field, but it was not found."} " at FSharp.Data.GraphQL.JsonValueHelper.helper@262-3(Boolean useOption, SchemaFieldInfo schemaField, JsonValue fieldValue) ...

### Repro steps
1. Download my .NET Core 3.1 (F#) Console application from GitHub: https://github.com/ZhenyaP/fsharp-graphql-client-sample
2. Make sure that in https://github.com/ZhenyaP/fsharp-graphql-client-sample/blob/master/BibliotekoClient/BibliotekoClient/GraphQLProviderCommon.fs, as the Server URL, the following is specified: https://bibliotekofunctions20200328112914.azurewebsites.net/GraphQL
3. Run the Console application
### Expected behavior
All GraphQL operations should run without exceptions
### Actual behavior
When executing getRegistriOperation.AsyncRun function, the above mentioned exception is thrown.

### Known workarounds
When running the same GraphQL query with passing Variable value of Custom Scalar type in GraphQL Playground, everything works fine.

### Related information 

* Operating system: Windows 10
* Branch: master (on GitHub: https://github.com/ZhenyaP/fsharp-graphql-client-sample)
* .NET Runtime, CoreCLR or Mono Version: .NET Core 3.1

**Comment by johnberzy-bazinga** [comment]
Can we close this now? I believe this was resolved by adding a custom json converter?

**Comment by xperiandri** [comment]
@johnberzy-bazinga, yes, we can close it
