### ISSUE TITLE
Use FusionTasks to eliminate boilerplate

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/FSharp.Data.GraphQL#276]
### Description

There is an amazing library [FusionTasks](https://github.com/kekyo/FSharp.Control.FusionTasks) that allows eliminating tasks awaiting boilerplate.
I think it worse to use it.

### Expected behavior

Bang operator of async workflow automatically awaits a `Task`.

### Actual behavior

`Async.AwaitTask` call is required to await a `Task`.

### Related information 

* FSharp.Data.GraphQL.Client 1.0.5

**Comment by johnberzy-bazinga** [comment]
I think a general rule of thumb is you want to minimize the number of dependencies a type provider has. Even though it might be convenient, this is probably not the right way to go.

**Comment by johnberzy-bazinga** [comment]
Closing as removing some boilerplate is not enough of a reason to take on additional dependencies in the Type Provider.
