### ISSUE TITLE
Unions in inputs

### ISSUE THREAD

**Issue by alexswan10k** [fsprojects/FSharp.Data.GraphQL#292]
### Description

I am trying to assign an input to a complex type - A Union. Specifically, I am trying to create a query DSL where I can define an object in the form:

```
type union = { Field: "A", Op: operator, Value: String } | {Field: "B", Op: operator, Value: Bool} | { Field: "C", Op: operator, Value: Complex } | { Combine: "And"|"Or", a: union, b: union }
```

Is this possible? There does not seem to be an API for Define.InputUnion or equivalent, and the Union type is not compatible with inputs, only outputs.

### Repro steps

N/A

### Expected behaviour

I should ideally be able to define an input union, perhaps something like 
```
let union = Define.InputUnion("name", [Input.A("")...]
let obj = Define.InputObject("obj", [Define.Input("unionFieldName", union))
```
### Actual behaviour

No behaviour, this is a build time question

### Known workarounds

None I can find

### Related information 

N/A

**Comment by jberzy** [comment]
@alexswan10k As Input Unions are not part of the spec it's not something we'll implement.

If you're looking for an alternative approach you can take a look at [this middleware](https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/src/FSharp.Data.GraphQL.Server.Middleware/MiddlewareDefinitions.fs#L64) that @ivelten created.

**Comment by alexswan10k** [comment]
@jberzy  thanks for clearing that up, apologies, having dug a bit deeper I did indeed find [this](https://github.com/graphql/graphql-spec/issues/488). I will close.

The middleware solution is an interesting approach and looks like it might get me mostly there. Am I right in understanding that this is actually modifying the schema, and thus will modify the generated metadata which tooling and code generators will read?

Is there any examples of how to use? I had a look for a sample in the git repo but no avail. Shall have a play with this anyway.

Thanks.

**Comment by laurencepettitt** [comment]
Seems [graphql-js](https://github.com/graphql/graphql-spec/pull/825#issuecomment-1697137074) and [HotChocolate](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/input-object-types/#oneof-input-objects) have already implemented this feature based on the RFC, which is in the process of [gathering feedback from libraries before merging](https://github.com/graphql/graphql-spec/pull/825#issuecomment-1660020765).

Is it a good time to also implement it here and start testing?

Would be a great addition!

**Comment by laurencepettitt** [comment]
Sorry, i just realised this is the wrong issue (this is for input unions, I was referring to oneOf input types), ill make another issue.
