### ISSUE TITLE
What would be nice is a simple walkthrough

### ISSUE THREAD

**Issue by MarkNicholls** [fsprojects/FSharp.Data.GraphQL#308]
Its a bit daunting. I have been doing some work in hot chocolate, which from my perspective is a maze of dependency injection, custom attributes and reflection, horrific to comprehend, but to be fair there are examples out there of how to set up a basic server.

This seems much better (from my perspective), but it really needs a nice simple, really dull, 

dotnet new ...
open in visual studio (not code)
f5
go to url xyz
paste in graphql 
execute
look at answer

style walkthrough.

I'd happily do it myself...but I don't really know where to start

**Comment by ltackmann** [comment]
Agree this looks like a really great project but its also unclear to me how one gets started. i.e creates a basic server on WebApi. If you enter the star-wars-example there are all sorts of helper files etc. are they all needed ?

**Comment by xperiandri** [comment]
Feel free to submit a PR with documentation improvement.
The GitHub package feed now contains a `dotnet new` template based on StarWarsAPI sample project

**Comment by valbers** [comment]
@MarkNicholls @ltackmann after you created this issue, support for instantly integrating a server into an ASP.NET (Giraffe) project has been added. There's a separate README for that with a minimal tutorial: https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/src/FSharp.Data.GraphQL.Server.AspNetCore/README.md
That tutorial is most probably not the walkthrough you've been hoping, but maybe it was the missing documentation piece for starting a GraphQL server?

**Comment by xperiandri** [comment]
Also, there is a `dotnet new` template available that creates your project from the StarWars sample

**Comment by valbers** [comment]
In order to keep our issues list manageable, I'm going to close this issue since it looks like it's not urgent anymore and there are "workarounds" available.
Hopefully there will be more resources available soon (blog posts) outside of the repository which will address the original request.
