### ISSUE TITLE
Looking for example using github api v4 https://api.github.com/graphql

### ISSUE THREAD

**Issue by markfirmware** [fsprojects/FSharp.Data.GraphQL#317]
something like

    type GraphQlClient = GraphQLProvider<"https://api.github.com/graphql">

**Comment by jberzy** [comment]
Have you taken a look at this?

https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/samples/client-provider/github_access.fsx

**Comment by markfirmware** [comment]
Swell! I had not known about the samples included in this repo.
