### ISSUE TITLE
Repo maintainers

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/FSharp.Data.GraphQL#359]
### Description

I suppose that as long as @jberzy no longer responds anywhere we need a new maintainer (or better two) who can operatively respond and give this project the right direction.

@dsyme could you help with that?

Maybe post a "call for maintainer" in the F# Org community?

At least me, @njlr and @mickhansen are interested in project support and evolution

**Comment by dsyme** [comment]
cc @sergey-tihon 

@xperiandri @njlr @mickhansen  Would any of you like to be maintainers?

Thanks

**Comment by xperiandri** [comment]
I do.
However, I would prefer if someone more experienced especially in type providers and GraphQL spec also will be involved.
@ivelten, @haf are you in?

**Comment by haf** [comment]
Hi, I did try to support the F# ecosystem for a long while (about 8 years) but it was impossible to make a living doing it. So I've moved on, sorry.

**Comment by mickhansen** [comment]
I'm using F# GraphQL as part of a work project and I recently had a chat with @jberzy and was added as a maintainer to the repository.

I will primarily be focusing on the Schema and Variable support part of the project (as shown here: https://github.com/fsprojects/FSharp.Data.GraphQL/pull/357) so would definitely suggest getting more maintainers.

The release process also still needs to be formalized, I come from open source work primarily in the Node.js world so a little green with Nuget, etc.

**Comment by xperiandri** [comment]
@mickhansen could you join https://foundation.fsharp.org/join ? So that you have F# Org Slack account?
And let's connect in Slack
I'm there with the same id

**Comment by nikhedonia** [comment]
Happy to help maintaining this library too!
I've been using F# and graphql in production and been helping companies to adapt them.

I'm also the co-author of [Fullstack GraphQL](https://newline.co/fullstack-graphql) and creator of [Buckaroo](https://gitHub.com/LoopPerfect/Buckaroo)

Would love to see this library have support for @defer and @stream directives

**Comment by dsyme** [comment]
@jberzy @nikhedonia @xperiandri @mickhansen  We should also trim down the number of people with maintenance/admin rights over this repo - currently there are 6, plus the 2 fsprojects backup maintainers.  

I think the four of you are the logical group of maintainers now?

**Comment by mickhansen** [comment]
> @jberzy @nikhedonia @xperiandri @mickhansen We should also trim down the number of people with maintenance/admin rights over this repo - currently there are 6, plus the 2 fsprojects backup maintainers.
> 
> I think the four of you are the logical group of maintainers now?

also @sgryt my colleague who will help review my PRs

**Comment by ivelten** [comment]
I would like to participate maintaining it. I've been looking for an opportunity to contribute to F# ecosystem.

**Comment by xperiandri** [comment]
@ivelten I've added you to the channel in F# Org Slack

**Comment by xperiandri** [comment]
By the way, to which account should @jberzy move NuGet packages? Because now he is an only owner and no one else can publish updated packages.
@dsyme

**Comment by dsyme** [comment]
@xperiandri The "fsprojects" org account on nuget is the right one to add as an owner.  Or add myself or @sergey-tihon

**Comment by xperiandri** [comment]
@jberzy could you do that, please?

**Comment by xperiandri** [comment]
Thanks, John!
