### ISSUE TITLE
Set `NuGet_Key` and `MyGet_Key` variables

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/FSharp.Data.GraphQL#379]
@sergey-tihon could you set variables?
NuGet_Key for https://www.nuget.org/profiles/fsprojects
MyGet_Key for https://www.myget.org/F/fsprojects
So that we add GitHub workflows for automated publishing

**Comment by sergey-tihon** [comment]
> NuGet_Key for https://www.nuget.org/profiles/fsprojects

Sorry, I cannot set the key fsproject organization here.
But if you give me the list of NuGet packages that you plan to publish and your NuGet user name, I will be able to add you as an owner of NuGet packages and then you generate the key for CI.

> MyGet_Key for https://www.myget.org/F/fsprojects

I do not have access there and I believe that it is no longer used. I would recommend using GitHub packages to pre-release/nightly builds https://github.com/orgs/fsprojects/packages No special keys are required to publish packages from GitHub Actions, just standard [GITHUB_TOKEN](https://github.com/fsprojects/FSharpx.Collections/blob/master/.github/workflows/dotnet.yml#L42) that is already available inside Actions.

**Comment by xperiandri** [comment]
@dsyme do you know who manages https://www.myget.org/F/fsprojects ?
I want to use it

**Comment by xperiandri** [comment]
@sergey-tihon I want to publish all `FSharp.Data.GraphQL` packages that are present on NuGet
* https://www.nuget.org/packages/FSharp.Data.GraphQL.Server
* https://www.nuget.org/packages/FSharp.Data.GraphQL.Client
* https://www.nuget.org/packages/FSharp.Data.GraphQL.Server.Middleware
* https://www.nuget.org/packages/FSharp.Data.GraphQL.Server.Middlewares 

My NuGet user name is the same @XperiAndri, email XperiAndri@Outlook.com

**Comment by sergey-tihon** [comment]
> https://www.nuget.org/packages/FSharp.Data.GraphQL.Server.Middlewares

I've send you owner invitation to first 3 packages, the last one is not owned by fsprojects.

> I want to use it

Why do you prefer MyGet over GitHub packages? GitHub Packages are better integrated with GiHub, it is easier to maintain, other org projects use them.

**Comment by xperiandri** [comment]
MyGet has UI

**Comment by xperiandri** [comment]
> I've send you owner invitation to first 3 packages, the last one is not owned by fsprojects.

Thanks!

**Comment by xperiandri** [comment]
But also I don't have rights to set secrets in this repo 🙂

**Comment by sergey-tihon** [comment]
please check again
