### ISSUE TITLE
Things to do before release 0.1-beta

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#60]
This is a roughly list of TODOs, we should finish before publishing first NuGet package:
- [x] Merge @alfonsogarciacaro Client PR with TypeProvider: #54
- [ ] Write down an API documentation
- [ ] Create a gitter channel for newcomers
- [ ] Stabilize a CI: remove unnecessary parts (eg. 2 separate CIs ;) ) + make sure that publishing pipeline can be done from FAKE script.
- [ ](Optional) Create a website and logo?

**Comment by alfonsogarciacaro** [comment]
I can write the script to generate the documentation from the XML comments as with other F# projects. Also, I can adapt the one we use in Fable to generate the website from MD docs. What do you think? Will the website be static (e.g. GH pages)? Or do we want to have some server-client interaction in it?

**Comment by Horusiath** [comment]
If we're going to create page from XML comments, we need to work on these as well ;) . 

I'd like to provide also some technical overview inside a documentation as well as API description - this would make an easier start for other contributors.

We could start with static site, and then move to something more dynamic if we'll need to.
