### ISSUE TITLE
Introduce query complexity analysis

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#65]
Right now we don't have a way to protect the server from executing too complex queries, that could possibly be dangerous (i.e. could consume all memory or CPU power). For this we should introduce complexity analysis: this have already been done in other GraphQL implementations such as [Sangria](http://sangria-graphql.org/learn/#protection-against-malicious-queries).

The core idea is an ability to add weight (complexity) value to each field, then compute the overall complexity of the query to decide what to do next before executing it. Complexity could be a property/method added to `ExecutionPlan`/`ExecutionPlanInfo` records.

I think it will be also a good idea to create some kind of interceptor method for schema, that will be executed before each operations on the root query start - this way we could trigger safety mechanism or execution plan mutation (see #64) in a single point.

**Comment by johnberzy-bazinga** [comment]
This is introduced as part of the Middleware additions.
