### ISSUE TITLE
Defining recursive types

### ISSUE THREAD

**Issue by OlegZee** [fsprojects/FSharp.Data.GraphQL#79]
I have a model containing mutually recursive references. E.g.
type Mailbox = { messages: Message array }
type Message = { author, date, subject, body, mailbox }

How could I define graphiql types matching this model?

**Comment by Horusiath** [comment]
You can define mutually recursive models using delayed field initialization, i.e:

``` fsharp
type Person = { Name: string; Friends: Person list }

let rec Person = Define.Object(
    name = "Person",
    fieldsFn = fun () -> [
        Define.Field("name", String, fun _ p -> p.Name)
        Define.Field("friends", ListOf Person, fun _ p -> p.Friends)
    ])
```

Simply use `let rec` + `and` to create definitions.

**Comment by OlegZee** [comment]
It works perfectly, thank you!

I've getting a bad experience with recursive objects in F# (as it lacks lazyness) while fsharp.data.grapiql is fine here. Also I see now I should have looked at the samples.
