### ISSUE TITLE
Respect schema guarantees in case of an errors

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#83]
Example - given following types:

``` graphql
schema {
  query: Query
}
type Query {
  person: Person
}
type Person {
  profile: Profile
}
type Profile {
  name: String!
  age: Int!
}
```

, when we execute a following query:

``` graphql
{
  person {
    profile {
      name # exception thrown during resolution
      age
    }
  }
}
```

We're getting an error message, but the `data.person.profile.name` value would be null, which is breaking the constraints of type system (as name is marked as NonNull String type). 

In regards to GraphQL implementation, the correct behavior is to elevate null up in the reply tree, to the first nullable point allowed - in this case `data.person.profile`. This means that even thou we have resolved age without errors, it shouldn't appear in the result set.

**Comment by johnberzy-bazinga** [comment]
This is taken care of as part of #119
