### ISSUE TITLE
Client: investigate new ways of generating typesafe queries

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#91]
I'm curious if it's possible to make GraphQL client queries a little nicer to use. I.e. currently equivalent of this query:

``` graphql
{
    hero(id: "1000") {
        name,
        friends {
            name
        }
        ... on Human {
            appearsIn
        }
    }
}
```

would be:

``` fsharp
GraphQlClient.Queries.Hero("1000", fun c -> Fields(
    c.name,
    Selection(c.friends, fun f -> Fields(
        f.name
    )),
    GraphQlClient.Types.Human.On(fun h -> Fields(
        h.appearsIn
    ))
))
```
## Option 1

Question is - could be make type provider, that would be able to produce computation expression on demand, based on incoming schema? Example:

``` fsharp
GraphQlClient.query "" {
    hero ("1000") {
        name
        friends {
            name
        }
        GraphQlClient.Types.Human.on {
            appearsIn
        }
    }
}
```

Is it even possbile?
## Option 2

In many cases the queries generated by the client are pretty static (look at how GraphQL is used with RelayJS). What we might want here is ability to provide type provider a query string along with the endpoint to a GraphQL server and order it to generate type tree, that will match not only the server schema itself, but also a query. 

Example:

Given type schema:

``` graphql
schema {
    query: Query
}

type Query {
    people: [Person!]!
}

type Person {
    firstName: String!
    lastName: String!
    friends: [Person!]
}
```

And some code:

``` fsharp
type GraphQlClient = GraphQLProvider<Endpoint="http://graphql-server.com", Query="""
    query GetPeople {
        people {
            firstName
        }
    }
    """>
async {
    let! data = GraphQlClient.Queries.GetPeople()
}
```

The `data` type would be actually list of:

``` fsharp
// generated by type provider
type GraphQlClient.QueryTypes.GetPeopleAnonymousObject { FirstName: string }
```

Thanks to that, we would be able to operate on `data` in fully typesafe manner, so we would have only the fields we want and don't risk any runtime errors.

**Comment by johnberzy-bazinga** [comment]
Closed as we actually implemented this now.
