### ISSUE TITLE
[Experimental] Support for subscriptions / live queries

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#92]
This issue will be used to track the state of pub/sub and live queries support in GraphQL.

Currently subscriptions or live queries are not part of official GraphQL specification. However some of the server implementations already try to support it. What is important to remember here:
- GraphQL don't have hard dependency on the transport layer. We should keep it this way.
- It shouldn't be tied to underlying subscription mechanism - if we want, we should be able to use in-memory subscription manager or replace it with i.e. Redis.
### How live queries differ from subscriptions

When making live query, server first returns data fitting requested GraphQL query. However when that data will change, it should calculate a correct diff between new state and the previously sent one, and send that diff to the client.

This is a lot heavier task that pub/sub, as server must keep track on what data has changed and be able to generate new deltas. It may bound server implementation to a specific technology and therefore should be implemented at the end.
### References
- [Subscriptions in GraphQL and Relay](http://graphql.org/blog/subscriptions-in-graphql-and-relay/)
- [GraphQL subscriptions in Apollo client](https://medium.com/apollo-stack/graphql-subscriptions-in-apollo-client-9a2457f015fb)
- [graphql.js support for subscriptions](https://github.com/graphql/graphql-js/pull/189)
- [Subscriptions model proposal](https://gist.github.com/OlegIlyenko/a5a9ab1b000ba0b5b1ad)

**Comment by johnberzy-bazinga** [comment]
Implemented in #55 and #110
