### ISSUE TITLE
[Experimental] Support for @defer directive

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#93]
This issue may be used to track state of `@defer` directive support in GraphQL. It's not yet part of the official spec.

Defer directive can be used to split returned data set into two parts - the one that needs to be returned immediately and other that can be returned after a while i.e. because that data doesn't need to be visible right away or it hides an expensive computation or I/O work underneath.

Example - let say we have following query:

``` graphql
query Example {
    post(id: "asdf") {
        ...author
        createdAt
        content
        likes
        comments @defer {
            ...author
            createdAt
            content
        }
    }
}

fragment author on Person {
    author {
        firstName
        lastName
    }
}
```

It's easy to imagine that we have some post here, that should be displayed as fast as possible. Beside that however, we can have it's comments, fetching which may be more expensive work. Therefore we're using `@defer` directive to mark that they can be returned later.

How this could be realized? My idea was to change return type of `schema.AsyncExecute` to return [AsyncSeq](http://fsprojects.github.io/FSharp.Control.AsyncSeq/) instead of `Async<>`. This way be could create an observable channel, when we could return subsequent parts of the query as they come. 

Structure returned by the first element would fit, what we know so far: `{ documentId: int; data: obj; errors: string list }`, but following elements would need to return patch data that could be nested within path known from the initial data: `{ path: obj list; data: obj}` i.e:

``` json
{
    "path": [ "post", 0, "comments" ],
    "data": {
        "author": {
            "firstName": "John",
            "lastName": "Smith"
        },
        "createdAt": "2016-10-02T07:51:24.508Z",
        "content": "foo bar"
    }
}
```

Givent that we could define a new returned data type as `AsyncSeq<GraphQlReply>` where:

``` fsharp
type GraphQLReply =
    | Init of documentId:uint64 * data:IReadOnlyDictionary<string, obj> * errors: string list
    | Deferred of path: obj list * data:IReadOnlyDictionary<string, obj>
```

Keep in mind that this is not a true code to be used (as we'd need to manage to serialize it into correct graphql JSON without introducing any explicit JSON lib dependencies).

In cases when endpoint doesn't allow partial updates (so basically every standard HTTP request), we can either fetch `Init` from from async seq and dispose it, or introduce a method, that will fetch all deferred updates until sequence completes and apply them on the initial result.
### References
- [Lee Byron's talk about defer directive](https://youtu.be/ViXL0YQnioU?t=12m41s)
- [graphql-ruby @defer support](https://github.com/rmosolgo/graphql-ruby/pull/168/files)

**Comment by johnberzy-bazinga** [comment]
See #117
