### ISSUE TITLE
Separate data structures for compilation phase

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/FSharp.Data.GraphQL#97]
Right now during the compilation phase we basically reuse type/field definitions made by the user - we basically attach a compiled execution function there. This is error prone and not particularly extensible. 

The idea here is to made additional series of types: `CompiledObject`, `CompiledField` etc. that will wrap user-provided definitions, and describe some additional fields like:
- `Execute` used instead of current FieldDef.Execute. This would potentially solve mutability problems noticed in #82
- `IsContextual` - this could be used to determine if a `FieldResolutionContext` object is necessary to be provided for a field resolve function. That flag can be easily set by analysis of resolve expression (see: #88).
- Other fields that could be used to speedup generation, we could discover necessary in the future.

**Comment by johnberzy-bazinga** [comment]
See #101
